### ISSUE TITLE
MVP Workshop

### ISSUE THREAD

**Issue by mrmetaverse** [AngellXR/metaversedev#13]
I think we should have a hackathon or workshop to brainstorm our first 1-3 course-paths.

_Originally posted by @mrmetaverse in https://github.com/AngellXR/metaversedev/discussions/9#discussioncomment-2503792_

**Comment by lalalune** [comment]
I think we have identified some technology to set up in a hackathon, which I am happy to take responsibility for deploying the blog engine. Maybe we could get some other folks to participate and create content, design, style, contribute code or whatever and try to hackathon a launch plan together.

**Comment by mrmetaverse** [comment]
@lalalune I made a little post on Twitter a short while ago, spread the word? 

https://twitter.com/mrmetaverse/status/1548322673993740290?s=20&t=VsvQByztT3WV2rEfIwDuvw

**Comment by mrmetaverse** [comment]
Archiving to focus on #22 and #21
