### ISSUE TITLE
Appoint project lead(s)

### ISSUE THREAD

**Issue by mrmetaverse** [AngellXR/metaversedev#4]
Who can spearhead this effort? We want to avoid bottlenecks, and definitely don't want a repeat of what just happened with the previous effort. There was some confusion about who is involved and what we are doing, and in the end, after months of work, the repo was seized and all members were kicked out. I will not waste my time again, especially since I was _super careful_ about setting expectations before I got involved in the first place. Therefore, we need appointed leadership, and no more risk of outside collaborators emotionally shutting down the effort. 

This effort matters. It can actually help people. There is no room for fear or ego.

**Comment by apolancojr** [comment]
Is there any reason why you can't be the sole administrator? 

You can then provision maintain, write, triage, and read rights against GitHub teams (My strong preference is to not assign rights to people [teams are almost always best].)

**Comment by mrmetaverse** [comment]
I agree about teams, just want to avoid becoming a bottleneck. Although, I'm happy to fill this role as needed.

**Comment by apolancojr** [comment]
It's less about bottleneck and more about preventing the org from being seized like your OP stated. I'm not aware of any way to prevent that unless you somehow create an admin login that requires a handshake from two different people.

**Comment by fire** [comment]
@mrmetaverse I suggest going futher. Have an archiving mirror of the work and a working repo similar to publishing scientific journals

**Comment by mrmetaverse** [comment]
That's a great idea @fire, if you're around on Monday, we are meeting at 5:05pm ET (21:05UTC)

**Comment by mrmetaverse** [comment]
During our meeting today, we agreed that I will continue to fill in this role, but we will always keep an eye out for potential project leads.
