### ISSUE TITLE
Select a Open Source License

### ISSUE THREAD

**Issue by mrmetaverse** [AngellXR/metaversedev#6]
I selected the MPL-2.0 for now, but think this group should review and discuss the selection, and make any changes we feel are necessary. 

![image](https://user-images.githubusercontent.com/63426722/147943634-7bb2f3e3-f32f-4d93-a870-3251f3ef510b.png)

**Comment by msub2** [comment]
Reference https://towardsdatascience.com/the-6-common-open-source-licenses-and-what-they-mean-715d434c2109

**Comment by mrmetaverse** [comment]
In interest of being open and accessible, we feel MIT is the best start. We may want apache in the future but MIT feels more than fine for now. 

>№4: MIT License
>Next up is many developers’ favorite license — including myself —[ the MIT license](https://opensource.org/licenses/MIT). The MIT license is a permissive license originally released by the Massachusetts Institute of Technology in the late ’80s. The reason many prefer this license is that it’s short, simply written, and clear about what is allowed and what’s not.
>The MIT license is one of the most used licenses in the open-source world today. Basically, this license allows you to do whatever you want to the licensed material as long as the original copyright and license are included in your work files. It removes any liability from authors and does not explicitly contain a patent grant.
